---
- name: list files in directory
#  become: true
#  become_exe: sudo su -
#  become_flags: ''
#  become_user: ''
  shell: 'ls -lrt'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"

- name: list files in directory
#  become: true
  shell: 'ls /opt/srlinux/python/virtual-env/lib/python3.6/site-packages/srlinux/mgmt/cli/plugins/reports/'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"

- name: copy files
  copy:
    src: "/home/henderiw/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: "0755"
  with_items:
    - in_error_brief.py
    - mtu_brief.py

- name: copy files
  copy:
    src: "/home/henderiw/{{ item }}"
    dest: "/opt/srlinux/python/virtual-env/lib/python3.6/site-packages/srlinux/mgmt/cli/plugins/reports/{{ item }}"
    mode: "0755"
  with_items:
    - in_error_brief.py
    - mtu_brief.py

- name: add entrypoint
#  become: true
  shell: 'cat /opt/srlinux/python/virtual-env/lib/python3.6/site-packages/srlinux-0.1-py3.6.egg-info/entry_points.txt'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"