---
- name: list files in directory
  become: true
  become_method: sudo su -
  shell: 'ls -lrt'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"

- name: list files in directory
  become: true
  shell: 'ls /opt/srlinux/python/virtual-env/lib/python3.6/site-packages/srlinux/mgmt/cli/plugins/reports/'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"

- name: add entrypoint
  become: true
  shell: 'cat /opt/srlinux/python/virtual-env/lib/python3.6/site-packages/srlinux-0.1-py3.6.egg-info/entry_points.txt'
  register: result

- name: debug output
  debug:
    msg: "{{result}}"